services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile
    image: hadoop-shared-baseimage
    ports:
      - "39870:9870"
      - "38088:8088"
      - "39000:9000"
    command: >
      bash -c "hdfs namenode & yarn resourcemanager "
    hostname: hdfs-namenode
    networks:
      - hadoop-network

  datanode:
    image: hadoop-shared-baseimage
    hostname: datanode
    depends_on:
      - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
      - "39864:9864"
    networks:
      - hadoop-network

  secondarynamenode:
    image: hadoop-shared-baseimage
    command: hdfs secondarynamenode
    depends_on:
      - namenode
    ports:
      - "39868:9868"
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge
