version: "3.7"
services:
  namenode:
    build: .
    ports:
      - "39870:9870"
      - "38088:8088"
    command: >
      bash -c "hdfs namenode & yarn resourcemanager "
    hostname: hdfs-namenode
    networks:
      - hadoop-network

  datanode:
    build: .
    hostname: datanode
    depends_on:
      - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
      - "39864:9864"
    networks:
      - hadoop-network

  secondarynamenode:
    build: .
    command: hdfs secondarynamenode
    ports:
      - "39868:9868"
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge
